# Generated by Django 3.2.9 on 2021-11-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
    ]
