# Generated by Django 3.2.9 on 2021-11-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
        ('buses', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passengers.passenger'),
        ),
    ]
